"""not null added

Revision ID: 0dd7b80f010f
Revises: b09ac8349839
Create Date: 2024-08-08 09:29:13.429224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd7b80f010f'
down_revision: Union[str, None] = 'b09ac8349839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'apartment_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'pet_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'pet_breed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'walk_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('orders', 'walk_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'walk_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('orders', 'walk_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('orders', 'pet_breed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'pet_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'apartment_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
