"""apartment_number->int

Revision ID: 3ce7319efbfb
Revises: 0dd7b80f010f
Create Date: 2024-08-08 14:52:26.792774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3ce7319efbfb'
down_revision: Union[str, None] = '0dd7b80f010f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'apartment_number',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    postgresql_using="apartment_number::integer",
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'apartment_number',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    postgresql_using="apartment_number::text",
                    existing_nullable=False)
    # ### end Alembic commands ###
