name: Meme API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  MODE: ${{ secrets.MODE }}
  LOG_LEVEL: ${{ secrets.LOG_LEVEL }}

  LOGIN_DB: ${{ secrets.LOGIN_DB }}
  PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
  NAME_DB: ${{ secrets.NAME_DB }}
  HOST_DB: ${{ secrets.HOST_DB }}
  PORT_DB: ${{ secrets.PORT_DB }}
  DIALECT_DB: ${{ secrets.DIALECT_DB }}
  DRIVER_DB: ${{ secrets.DRIVER_DB }}

  TEST_LOGIN_DB: ${{ secrets.TEST_LOGIN_DB }}
  TEST_PASSWORD_DB: ${{ secrets.TEST_PASSWORD_DB }}
  TEST_NAME_DB: ${{ secrets.TEST_NAME_DB }}
  TEST_HOST_DB: ${{ secrets.TEST_HOST_DB }}
  TEST_PORT_DB: ${{ secrets.TEST_PORT_DB }}

  HOST_REDIS: ${{ secrets.HOST_REDIS }}

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ secrets.TEST_LOGIN_DB }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_PASSWORD_DB }}
          POSTGRES_DB: ${{ secrets.TEST_NAME_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('public_memes_api/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: test dao methods
        run: |
          pytest -v -s -p no:warnings app/tests/integration_tests/dao_test.py

      - name: test api endpoints
        run: |
          pytest -v -s -p no:warnings app/tests/integration_tests/api_test.py